### ISSUE TITLE
How to set sip account?

### ISSUE THREAD

**Issue by apolloyang2017** [tomek-o/STM32-SIP#2]
Would you tell me how to set the sip server ip address and sip user account？

**Comment by tomek-o** [comment]
sip_ua.c, look for app_start() / ua_add() function. Above ua_add() adding "local" account there is some disabled code coming from tSIP and handling more cases that can be used as reference but would need to be rewritten to plain C.

**Comment by tomek-o** [comment]
Update: account configuration example and fixed related to DNS client are included among latest commits.
